---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    cisco.ios.ios_banner:
      banner: login
      text: |
        hola a todos guapisimos aqui vegeta 777777
      state: present

